### ISSUE TITLE
Error compiling.

### ISSUE THREAD

**Issue by jsarasin** [andrewhickman/vulkano-glyph#1]
Hey there,
Thanks for making this!

I got the following error while trying to cargo run --example=basic
```
error[E0308]: mismatched types
  --> src/cache.rs:83:9
   |
81 |       ) -> result::Result<(), CacheWriteErr> {
   |            --------------------------------- expected `std::result::Result<(), rusttype::gpu_cache::CacheWriteErr>` because of return type
82 |           let GpuCache { cache, buf, img } = self;
83 | /         cache.cache_queued(|rect, data| {
84 | |             let cmd = match result {
85 | |                 Ok(cmd) => cmd.take(),
86 | |                 Err(_) => return,
...  |
89 | |             *result = upload(rect, data, queue, cmd, img, buf).map(Some);
90 | |         })
   | |__________^ expected (), found enum `rusttype::gpu_cache::CachedBy`
   |
   = note: expected type `std::result::Result<(), _>`
              found type `std::result::Result<rusttype::gpu_cache::CachedBy, _>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `vulkano-glyph`.

To learn more, run the command again with --verbose.

```

I was able to get it working fine by adding a Ok(()) at the end of the function. Still giving a warning but seems to be working fine. 

Trying to compile with:
```
james@netbook:~/Code/vulkano-glyph$ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
```

Not sure the best way to deal with this.

**Comment by andrewhickman** [comment]
Looks like the return type changed in the latest rusttype version. You should be able to pin rusttype to version 0.7.4 in your cargo.lock to fix it.

I'll publish a fix later today.

**Comment by jsarasin** [comment]
Cool. I have updated vulkano_shader_derive and vulkano to 0.11 in my fork. Just a minor change to the shaders. Want a pull request?

**Comment by andrewhickman** [comment]
Yes please!

**Comment by jsarasin** [comment]
For sure! I'd like to update the necessary rusttype code if you have a direction you'd like to go.
I came across your repo while trying to figure out why they require a cache_queued and and friends _every single frame_.
Have yet to see how you deal with that. Any insight into this? I'm pretty new to Vulkan but it seems terribly unnecessary and a slight performance drain.

**Comment by andrewhickman** [comment]
`cache_queued` takes a callback which only gets called if there are actually new glyphs to upload, so it should usually be a fairly cheap operation.

**Comment by jsarasin** [comment]
Ok I'll add that and remove the font, might not be able to get to it until
tonight.
Cool!
