### ISSUE TITLE
Use Semver's in Dependencies

### ISSUE THREAD

**Issue by knappador** [andrewhickman/vulkano-glyph#3]
Dependency maintenance in downstream, especially around vulkano, should opt for more permissive versions.  0.11.1 is out.  Since this library uses pretty high level API's, better to make it responsive to upstream.

https://github.com/andrewhickman/vulkano-glyph/blob/79a6d1c4f15757e6e96985c97d2c87854d4d4164/Cargo.toml#L12

https://crates.io/crates/vulkano

**Comment by andrewhickman** [comment]
`0.11.0` should be equivalent to `^0.11.0`, which is be compatible with `0.11.1`

**Comment by knappador** [comment]
Confirmed.  Closing.

How do you like the vulkano-text implementation?  You both appear to be using rusttype to get your buffers populated.  https://github.com/rukai/vulkano-text/blob/master/Cargo.toml

The API over there seems to be more fancy, but I haven't looked at the guts to try to judge future fitness.

**Comment by andrewhickman** [comment]
vulkano-text seems mostly designed for quick prototyping, since it only lets you use the Deja Vu font. It also doesn't have any control over text layout whereas this library can potentially be used with something like https://crates.io/crates/glyph_brush_layout

**Comment by jsarasin** [comment]
I found it trashed my framerate and very inflexible. Honestly though it
seems trying to make a generic wrapper like these isn't the most feasible
idea.
